const lcuState = window.LCU?.State || {};

const lcuStateDefaults = {
    Location: 'Charleston, SC 29412',
    RefreshRate: 30000,
    IsDark: false,
    DisplayHero: 'none',
    PointAPIQuery: '/api/v0/point-query',
    VariablesAPIQuery: '/api/v0/api-variables',
    HabistackAPIRoot: '/api/habistack',
    GeocodioAPIRoot: '/api/geocodio',
    GeocodioQuery: '/geocode',
    IoTAPIQuery: '/WarmQuery?',
    IoTEmulated: 'false',
    IoTPages: '&page=1&pageSize=100',
    IoTAPIRoot: '/api/iot',
    SelectedVariables: [
        'Temperature_Surface',
        'Temperature_2Meters',
        'PrecipitationRateMillisHr_Surface',
        'PrecipitationRate_Surface',
        'TotalPrecipitation_Surface',
        'WindGust_Surface',
        'WindSpeed_10Meters',
        'WindDirection_10Meters',
        'ShortWaveRadiation_Surface',
        'LongWaveRadiation_Surface',
        'DewPoint_2Meters',
        'Pressure_Surface',
        'Visibility_Surface',
        'CloudCover_EntireAtmosphere'
    ],
    DefaultChartPrefs: [
        {
            Mode: 'Light',
            ChartType: 'Line',
            BackgroundColor: 'rgb(0, 0, 0, 0.4)',
            BorderColor: 'rgb(0, 0, 0, 0.4)',
            Options: { scales: { y: { grid: { color: 'rgb(0, 0, 0, 0.1)' } }, x: { grid: { color: 'rgb(0, 0, 0, 0.1)' } } } }
        },
        {
            Mode: 'Dark',
            ChartType: 'Line',
            BackgroundColor: 'rgb(255, 255, 255, 0.4)',
            BorderColor: 'rgb(255, 255, 255, 0.4)',
            Options: { scales: { y: { grid: { color: 'rgb(255, 255, 255, 0.1)' } }, x: { grid: { color: 'rgb(255, 255, 255, 0.1)' } } } }
        },
        {
            Mode: 'Light',
            ChartType: 'Bar',
            BackgroundColor: 'rgb(0, 0, 0, 0.4)',
            BorderColor: 'rgb(0, 0, 0, 0.4)',
            Options: { scales: { y: { grid: { color: 'rgb(0, 0, 0, 0.1)' } }, x: { grid: { color: 'rgb(0, 0, 0, 0.1)' } } } }
        },
        {
            Mode: 'Dark',
            ChartType: 'Bar',
            BackgroundColor: 'rgb(255, 255, 255, 0.4)',
            BorderColor: 'rgb(255, 255, 255, 0.4)',
            Options: { scales: { y: { grid: { color: 'rgb(255, 255, 255, 0.1)' } }, x: { grid: { color: 'rgb(255, 255, 255, 0.1)' } } } }
        }
    ],
    ChartPrefs: [
        {
            Name: 'Temperature (Surface)',
            ConvertUnits: 'kelvinToFahrenheit',
            DisplayUnits: '°F',
            CurrentFirstPlace: true,
            DisplayCurrent: true,
            Icons: ['temperature'],
            IconColors: ['blue', 'yellow', 'red'],
            IconSize: ['3em'],
            IconValues: [80, 88, 100],
            ChartType: 'Line',
            BackgroundColor: 'rgb(255, 0, 30)',
            BorderColor: 'rgb(240, 0, 30)',
            Options: { scales: { y: { beginAtZero: false } } }
        },
        {
            Name: 'Temperature (2Meters)',
            ConvertUnits: 'kelvinToFahrenheit',
            DisplayUnits: '°F',
            CurrentFirstPlace: true,
            DisplayCurrent: true,
            Icons: ['emptytemperature', 'temperature', 'temperature'],
            IconColors: ['blue', 'yellow', 'red'],
            IconSize: ['3em'],
            IconValues: [80, 90, 100],
            ChartType: 'Line',
            BackgroundColor: 'rgb(255, 0, 30)',
            BorderColor: 'rgb(240, 0, 30)',
            Options: { scales: { y: { beginAtZero: false } } }
        },
        {
            Name: 'PrecipitationRateMillisHr (Surface)',
            DisplayUnits: 'mm/hr',
            ConvertUnits: 'roundToHundThou',
            ChartType: 'Bar',
            CurrentFirstPlace: true,
            DisplayCurrent: true,
            Icons: ['showers', 'warning'],
            IconColors: ['lightblue', 'red'],
            IconSize: ['3em'],
            IconValues: [0, 5],
            BackgroundColor: 'rgb(0, 0, 240)',
            BorderColor: 'rgb(0, 0, 210)',
            Options: { scales: { y: { beginAtZero: true } } }
        },
        {
            Name: 'PrecipitationRate (Surface)',
            DisplayUnits: 'kg/m²/s',
            ConvertUnits: 'roundToHundThou',
            ChartType: 'Bar',
            CurrentFirstPlace: true,
            DisplayCurrent: true,
            Icons: ['showers', 'warning'],
            IconColors: ['lightblue', 'red'],
            IconSize: ['3em'],
            IconValues: [0, 5],
            BackgroundColor: 'rgb(0, 0, 240)',
            BorderColor: 'rgb(0, 0, 210)',
            Options: { scales: { y: { beginAtZero: true } } }
        },
        {
            Name: 'TotalPrecipitation (Surface)',
            DisplayUnits: 'kg/m²/s',
            ConvertUnits: 'roundToHundThou',
            ChartType: 'Bar',
            CurrentFirstPlace: true,
            DisplayCurrent: true,
            Icons: ['rain', 'warning'],
            IconColors: ['lightblue', 'red'],
            IconSize: ['3em'],
            IconValues: [0, 10],
            BackgroundColor: 'rgb(0, 0, 240)',
            BorderColor: 'rgb(0, 0, 210)',
            Options: { scales: { y: { beginAtZero: true } } }
        },
        {
            Name: 'WindSpeed (10Meters)',
            DisplayUnits: 'MPH',
            ConvertUnits: 'mSecToMPH',
            ChartType: 'Line',
            CurrentFirstPlace: true,
            DisplayCurrent: true,
            Icons: ['wind', 'warning'],
            IconColors: ['green', 'red'],
            IconSize: ['3em'],
            IconValues: [20, 35],
            BackgroundColor: 'rgb(0, 255, 0)',
            BorderColor: 'rgb(0, 220, 0)',
            Options: { scales: { y: { beginAtZero: true } } }
        },
        {
            Name: 'WindGust (Surface)',
            DisplayUnits: 'MPH',
            ConvertUnits: 'mSecToMPH',
            ChartType: 'Line',
            CurrentFirstPlace: true,
            DisplayCurrent: true,
            Icons: ['gusts', 'warning'],
            IconColors: ['green', 'red'],
            IconSize: ['3em'],
            IconValues: [30, 50],
            BackgroundColor: 'rgb(0, 230, 0)',
            BorderColor: 'rgb(0, 200, 0)',
            Options: { scales: { y: { beginAtZero: true } } }
        },
        {
            Name: 'WindDirection (10Meters)',
            DisplayUnits: '°DEG',
            ConvertUnits: 'roundToTens',
            ChartType: 'Line',
            CurrentFirstPlace: true,
            DisplayCurrent: true,
            Icons: ['arrowup', 'arrowupright', 'arrowright', 'arrowdownright', 'arrowdown', 'arrowdownleft', 'arrowleft', 'arrowupleft', 'arrowup'],
            IconColors: ['green'],
            IconSize: ['2.5em'],
            IconValues: [0, 30, 75, 120, 165, 210, 255, 300, 345, 360],
            BackgroundColor: 'rgb(0, 220, 0)',
            BorderColor: 'rgb(0, 200, 0)',
            Options: { scales: { y: { beginAtZero: true } } }
        },
        {
            Name: 'ShortWaveRadiation (Surface)',
            DisplayUnits: 'W/m²',
            ConvertUnits: 'roundToTens',
            CurrentFirstPlace: true,
            DisplayCurrent: true,
            Icons: ['sun', 'warning'],
            IconColors: ['yellow', 'red'],
            IconSize: ['3em'],
            IconValues: [100, 200],
            ChartType: 'Line',
            BackgroundColor: 'rgb(255, 255, 30)',
            BorderColor: 'rgb(240, 240, 30)',
            Options: { scales: { y: { beginAtZero: true } } }
        },
        {
            Name: 'LongWaveRadiation (Surface)',
            DisplayUnits: 'W/m²',
            ConvertUnits: 'roundToTens',
            CurrentFirstPlace: true,
            DisplayCurrent: true,
            Icons: ['sunheat', 'warning'],
            IconColors: ['orange', 'red'],
            IconSize: ['3em'],
            IconValues: [100, 400],
            ChartType: 'Line',
            BackgroundColor: 'rgb(255, 255, 30)',
            BorderColor: 'rgb(240, 240, 30)',
            Options: { scales: { y: { beginAtZero: true } } }
        },
        {
            Name: 'DewPoint (2Meters)',
            ConvertUnits: 'kelvinToFahrenheit',
            DisplayUnits: '°F',
            CurrentFirstPlace: true,
            DisplayCurrent: true,
            Icons: ['water'],
            IconColors: ['lightblue'],
            IconSize: ['2em'],
            IconValues: [80],
            ChartType: 'Line',
            BackgroundColor: 'rgb(55, 100, 250)',
            BorderColor: 'rgb(40, 100, 220)',
            Options: { scales: { y: { beginAtZero: false } } }
        },
        {
            Name: 'Pressure (Surface)',
            ConvertUnits: 'paToKpa',
            DisplayUnits: 'kPa',
            CurrentFirstPlace: true,
            DisplayCurrent: true,
            Icons: ['gauge'],
            IconColors: ['lightblue'],
            IconSize: ['2.5em'],
            IconValues: [80],
            ChartType: 'Line',
            BackgroundColor: 'rgb(55, 100, 240)',
            BorderColor: 'rgb(40, 100, 210)',
            Options: { scales: { y: { beginAtZero: false } } }
        },
        {
            Name: 'Visibility (Surface)',
            DisplayUnits: 'Miles',
            ConvertUnits: 'metersToMiles',
            ChartType: 'Line',
            CurrentFirstPlace: true,
            DisplayCurrent: true,
            Icons: ['invisible', 'visible'],
            IconColors: ['red', 'lightgrey'],
            IconSize: ['2.5em'],
            IconValues: [0, 3],
            BackgroundColor: 'rgb(120, 120, 200)',
            BorderColor: 'rgb(120, 120, 210)',
            Options: { scales: { y: { beginAtZero: true } } }
        },
        {
            Name: 'CloudCover (EntireAtmosphere)',
            DisplayUnits: '%',
            ConvertUnits: 'roundToTens',
            ChartType: 'Line',
            CurrentFirstPlace: true,
            DisplayCurrent: true,
            Icons: ['cloud'],
            IconColors: ['lightgrey'],
            IconSize: ['3em'],
            IconValues: [100],
            BackgroundColor: 'rgb(120, 120, 200)',
            BorderColor: 'rgb(120, 120, 210)',
            Options: { scales: { y: { beginAtZero: true } } }
        },
        {
            Name: 'AX',
            ChartType: 'Line',
            DisplayUnits: 'X m/s²',
            DisplayCurrent: true,
            Icons: ['rocket'],
            IconColors: ['red'],
            IconSize: ['3em'],
            IconValues: [0],
            BackgroundColor: 'rgb(180, 0, 0)',
            BorderColor: 'rgb(180, 0, 0)',
            Options: { scales: { y: { beginAtZero: false } } }
        },
        {
            Name: 'AY',
            ChartType: 'Line',
            DisplayUnits: 'Y m/s²',
            DisplayCurrent: true,
            Icons: ['rocket'],
            IconColors: ['red'],
            IconSize: ['3em'],
            IconValues: [0],
            BackgroundColor: 'rgb(180, 0, 0)',
            BorderColor: 'rgb(180, 0, 0)',
            Options: { scales: { y: { beginAtZero: false } } }
        },
        {
            Name: 'AZ',
            ChartType: 'Line',
            DisplayUnits: 'Z m/s²',
            DisplayCurrent: true,
            Icons: ['rocket'],
            IconColors: ['red'],
            IconSize: ['3em'],
            IconValues: [0],
            BackgroundColor: 'rgb(180, 0, 0)',
            BorderColor: 'rgb(180, 0, 0)',
            Options: { scales: { y: { beginAtZero: false } } }
        },
        {
            Name: 'GX',
            ChartType: 'Line',
            DisplayUnits: 'X',
            DisplayCurrent: true,
            Icons: ['rotate3d'],
            IconColors: ['green'],
            IconSize: ['3em'],
            IconValues: [0],
            BackgroundColor: 'rgb(0, 180, 0)',
            BorderColor: 'rgb(0, 180, 0)',
            Options: { scales: { y: { beginAtZero: false } } }
        },
        {
            Name: 'GY',
            ChartType: 'Line',
            DisplayUnits: 'Y',
            DisplayCurrent: true,
            Icons: ['rotate3d'],
            IconColors: ['green'],
            IconSize: ['3em'],
            IconValues: [0],
            BackgroundColor: 'rgb(0, 180, 0)',
            BorderColor: 'rgb(0, 180, 0)',
            Options: { scales: { y: { beginAtZero: false } } }
        },
        {
            Name: 'GZ',
            ChartType: 'Line',
            DisplayUnits: 'Z',
            DisplayCurrent: true,
            Icons: ['rotate3d'],
            IconColors: ['green'],
            IconSize: ['3em'],
            IconValues: [0],
            BackgroundColor: 'rgb(0, 180, 0)',
            BorderColor: 'rgb(0, 180, 0)',
            Options: { scales: { y: { beginAtZero: false } } }
        },
        {
            Name: 'MX',
            ChartType: 'Line',
            DisplayUnits: 'X',
            DisplayCurrent: true,
            Icons: ['magnet'],
            IconColors: ['blue'],
            IconSize: ['3em'],
            IconValues: [0],
            BackgroundColor: 'rgb(0, 0, 180)',
            BorderColor: 'rgb(0, 0, 180)',
            Options: { scales: { y: { beginAtZero: false } } }
        },
        {
            Name: 'MY',
            ChartType: 'Line',
            DisplayUnits: 'Y',
            DisplayCurrent: true,
            Icons: ['magnet'],
            IconColors: ['blue'],
            IconSize: ['3em'],
            IconValues: [0],
            BackgroundColor: 'rgb(0, 0, 180)',
            BorderColor: 'rgb(0, 0, 180)',
            Options: { scales: { y: { beginAtZero: false } } }
        },
        {
            Name: 'MZ',
            ChartType: 'Line',
            DisplayUnits: 'Z',
            DisplayCurrent: true,
            Icons: ['magnet'],
            IconColors: ['blue'],
            IconSize: ['3em'],
            IconValues: [0],
            BackgroundColor: 'rgb(0, 0, 180)',
            BorderColor: 'rgb(0, 0, 180)',
            Options: { scales: { y: { beginAtZero: false } } }
        },
        {
            Name: 'EA',
            ChartType: 'Line',
            DisplayUnits: 'EDA',
            DisplayCurrent: true,
            Icons: ['default'],
            IconColors: ['gray'],
            IconSize: ['3em'],
            IconValues: [0],
            BackgroundColor: 'rgb(120, 120, 120)',
            BorderColor: 'rgb(120, 120, 120)',
            Options: { scales: { y: { beginAtZero: false } } }
        },
        {
            Name: 'EL',
            ChartType: 'Line',
            DisplayUnits: 'EDL',
            DisplayCurrent: true,
            Icons: ['default'],
            IconColors: ['gray'],
            IconSize: ['3em'],
            IconValues: [0],
            BackgroundColor: 'rgb(120, 120, 120)',
            BorderColor: 'rgb(120, 120, 120)',
            Options: { scales: { y: { beginAtZero: false } } }
        },
        {
            Name: 'ER',
            ChartType: 'Line',
            DisplayUnits: 'EDR',
            DisplayCurrent: true,
            Icons: ['default'],
            IconColors: ['gray'],
            IconSize: ['3em'],
            IconValues: [0],
            BackgroundColor: 'rgb(120, 120, 120)',
            BorderColor: 'rgb(120, 120, 120)',
            Options: { scales: { y: { beginAtZero: false } } }
        },
        {
            Name: 'H0',
            ChartType: 'Line',
            DisplayUnits: '%',
            DisplayCurrent: true,
            Icons: ['water'],
            IconColors: ['lightblue'],
            IconSize: ['2em'],
            IconValues: [0],
            BackgroundColor: 'rgb(120, 120, 120)',
            BorderColor: 'rgb(120, 120, 120)',
            Options: { scales: { y: { beginAtZero: false } } }
        },
        {
            Name: 'T0',
            ChartType: 'Line',
            DisplayUnits: '°C',
            DisplayCurrent: true,
            Icons: ['temperature'],
            IconColors: ['red'],
            IconSize: ['3em'],
            IconValues: [0],
            BackgroundColor: 'rgb(240, 0, 0)',
            BorderColor: 'rgb(240, 0, 0)',
            Options: { scales: { y: { beginAtZero: false } } }
        },
        {
            Name: 'TH',
            ChartType: 'Line',
            DisplayUnits: '°C',
            DisplayCurrent: true,
            Icons: ['temperature'],
            IconColors: ['red'],
            IconSize: ['3em'],
            IconValues: [0],
            BackgroundColor: 'rgb(240, 0, 0)',
            BorderColor: 'rgb(240, 0, 0)',
            Options: { scales: { y: { beginAtZero: false } } }
        },
        {
            Name: 'PI',
            ChartType: 'Line',
            DisplayUnits: 'PPG INFRARED',
            DisplayCurrent: true,
            Icons: ['heartmonitor'],
            IconColors: ['red'],
            IconSize: ['3em'],
            IconValues: [0],
            BackgroundColor: 'rgb(180, 0, 0)',
            BorderColor: 'rgb(180, 0, 0)',
            Options: { scales: { y: { beginAtZero: false } } }
        },
        {
            Name: 'PR',
            ChartType: 'Line',
            DisplayUnits: 'PPG RED',
            DisplayCurrent: true,
            Icons: ['heart'],
            IconColors: ['red'],
            IconSize: ['3em'],
            IconValues: [0],
            BackgroundColor: 'rgb(240, 0, 0)',
            BorderColor: 'rgb(240, 0, 0)',
            Options: { scales: { y: { beginAtZero: false } } }
        },
        {
            Name: 'PG',
            ChartType: 'Line',
            DisplayUnits: 'PPG GREEN',
            DisplayCurrent: true,
            Icons: ['heart'],
            IconColors: ['green'],
            IconSize: ['3em'],
            IconValues: [0],
            BackgroundColor: 'rgb(0, 240, 0)',
            BorderColor: 'rgb(0, 240, 0)',
            Options: { scales: { y: { beginAtZero: false } } }
        },
        {
            Name: 'BV',
            ChartType: 'Line',
            DisplayUnits: 'volts',
            DisplayCurrent: true,
            Icons: ['batteryvoltage'],
            IconColors: ['Green'],
            IconSize: ['3em'],
            IconValues: [0],
            BackgroundColor: 'rgb(120, 120, 120)',
            BorderColor: 'rgb(120, 120, 120)',
            Options: { scales: { y: { beginAtZero: true } } }
        },
        {
            Name: 'BP',
            ChartType: 'Line',
            DisplayUnits: '%',
            DisplayCurrent: true,
            Icons: ['batteryempty','battery15full','battery30full','battery45full','battery60full','battery75full','battery90full','batteryfull'],
            IconColors: ['Red','Red','Orange','Orange','Green','Green','Green','Green'],
            IconValues: [0,15,30,45,60,75,90,100],
            BackgroundColor: 'rgb(120, 120, 120)',
            BorderColor: 'rgb(120, 120, 120)',
            Options: { scales: { y: { beginAtZero: true } } }
        }
    ],
    HeroPrefs: [
        {
            Name: 'Ski',
            StringName: 'word',
            BooleanName: true,
            Background: ['Snow', 'SnowSmall' ]
        },
        {
            Name: 'Energy',
            StringName: 'word',
            BooleanName: true,
            Background: ['Energy', 'SnowSmall' ]
        },
    ]
};

// const LCUState = lcuState || lcuStateDefaults;
let LCUState = lcuStateDefaults;

LCUState = {
    ...lcuStateDefaults,
    ...(lcuState || {})
};

export default LCUState;